language: julia
os:
  - linux

dist: xenial

julia:
  - 1.0.1

python:
  - "3.6"

notifications:
  email: false


before_install:
  - sudo apt-get update
  - sudo apt-get install ffmpeg qt5-default
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip
  - sudo -H pip3 install --upgrade pip
  - sudo -H pip3 install sympy
  - sudo -H pip3 install matplotlib

#install:

script:
  #- julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("$pkgname"); Pkg.test("$pkgname"; coverage=false)'
