language: julia
os:
  - linux

dist: xenial

julia:
  - 1.0.1

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:mc3man/trusty-media'
    packages:
      - ffmpeg

addons:
  apt:
    sources:
      - sourceline: 'ppa:deadsnakes/ppa'
    packages:
      - "python3.6"
      #- "python3-pip"

before_install:
  - sudo apt-get update
  - sudo apt-get install qt5-defaul
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  #- sudo pip3 install --upgrade setuptools
  - sudo pip3 install matplotlib
  #- git clone https://github.com/mexsser/POMDPIDMModel.jl POMDPIDMModel && cd "$_"

install:
  #- julia --color=yes -i -O -- deps/build.jl

after_success:
  - julia -e 'import POMDPIDMModel; cd(joinpath(dirname(pathof(POMDPIDMModel)), "..", "test"))';
  - julia --color=yes -i -O -- runtests.jl
