language: julia
os:
  - linux

dist: xenial

julia:
  - 1.0.1

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/python-3.6'
    packages:
      - "python3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install ffmpeg qt5-default
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  - sudo pip3 install matplotlib
  - git clone https://github.com/mexsser/POMDPIDMModel.jl POMDPIDMModel && cd "$_"

install:
  - rm -rf ~/.julia/*
  - julia --color=yes -i -- deps/build.jl

script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url = "https://github.com/mexsser/POMDPIDMModel.jl"))'

after_success:
  - julia -e 'import POMDPIDMModel; cd(joinpath(dirname(pathof(POMDPIDMModel)), "..", "test"))';
  - julia --color=yes -i -O -- runtests.jl
