language: julia
os:
  - linux

julia:
  - 1.0.1

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:mc3man/trusty-media'
    packages:
      - ffmpeg


before_install:
  - sudo apt-get update
  - sudo apt-get install qt5-default
  - sudo pip3 install matplotlib
  - git clone https://github.com/mexsser/POMDPIDMModel.jl POMDPIDMModel && cd "$_"
  - julia --color=yes -i -O -- deps/build.jl

after_success:
  - julia -e 'import POMDPIDMModel; cd(joinpath(dirname(pathof(POMDPIDMModel)), "..", "test"))';
  - julia --color=yes -i -O -- runtests.jl
